version: "2.2"

services:
    server:
        image: node:12.6.0-stretch
        command: bash -c 'sleep 3 && cd /app/server && npm start'
#        command: bash -c 'sleep 10000'
        volumes:
            - '.:/app'
        environment:
            - NODE_ENV=${NODE_ENV}
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - 8888:80
        networks:
            - webnet

    database:
        image: postgres:11.4
        environment:
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
        networks:
            - webnet

networks:
  webnet: