version: "2.2"

services:
    server:
        image: nodejstesttask:1.0.0
        command: bash -c "sleep 1 && npm start"
        build:
            context: .
        volumes:
            - '.:/app'
        environment:
            - NODE_ENV=${NODE_ENV}
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - 8888:80
        networks:
            - webnet

    database:
        image: postgres:11.4
        environment:
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
        networks:
            - webnet

networks:
  webnet: